services:

  mongo:
    image: mongo # MongoDB image - banco de sados
    restart: always
    ports:
      - 27018:27017 # a porta 27017 do container será mapeada para a porta 27017 do host 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

